#!/usr/bin/env python3
"""What `sweep.py` claims about footers and `WORK/` notes, as tests rather than
as prose.

Run: python3 -m unittest discover -s .agents/skills/sweep -p 'test_*.py'
"""
import os
import pathlib
import tempfile
import unittest
import contextlib
import http.client
import io
import json
import urllib.error
import urllib.request

import sweep


class Footer(unittest.TestCase):
    """Every marker in AGENT_FOOTERS is current. Each agent's runtime appends
    its own and the agent does not choose it, so the sweep recognises all of
    them or it reports our own replies as USER's unanswered questions."""

    def setUp(self):
        self.setup = {
            "USER": "toumix",
            "AGENT_FOOTERS": ["claude.ai/code", "Generated by Codex"],
        }

    def comment(self, body, user="toumix"):
        return {"body": body, "user": {"login": user}}

    def test_the_configured_file_lists_both_runtimes(self):
        self.assertEqual(sweep.config(sweep.find_config())["AGENT_FOOTERS"],
                         ["claude.ai/code", "Generated by Codex"])

    def test_a_bare_marker_on_the_last_line_answers(self):
        self.assertTrue(sweep.answered(
            self.comment("Done.\n\nGenerated by Codex"), self.setup))

    def test_a_link_label_never_answers_however_exactly_it_reads(self):
        """The label is the half a human types and the target is the half the
        runtime emits, so a matching label over any destination would let a
        comment silence its own thread."""
        self.assertFalse(sweep.answered(self.comment(
            "Done.\n\n[Generated by Codex](https://anywhere-at-all.example)"),
            self.setup))

    def test_a_runtime_wanting_a_linked_footer_lists_its_url_token(self):
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n[Generated by Codex](https://chatgpt.com/share/example)"),
            {**self.setup, "AGENT_FOOTERS": [*self.setup["AGENT_FOOTERS"],
                                             "chatgpt.com/share"]}))

    def test_a_url_marker_inside_the_link_target_answers(self):
        """Claude Code's mandated footer, which no Claude session can opt out
        of: the marker is a fragment of the href, wrapped in emphasis."""
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n_Generated by [Claude Code](https://claude.ai/code)_"),
            self.setup))

    def test_a_session_id_in_the_target_still_answers(self):
        self.assertTrue(sweep.answered(self.comment(
            "Done.\n\n_Generated by [Claude Code]"
            "(https://claude.ai/code/session_01U5t8qLxoQZ6VHAuEDoU6zm)_"),
            self.setup))

    def test_a_marker_in_prose_does_not_answer(self):
        self.assertFalse(sweep.answered(self.comment(
            "This line mentions Generated by Codex in prose."), self.setup))

    def test_a_marker_must_be_on_the_final_line(self):
        self.assertFalse(sweep.answered(self.comment(
            "Generated by Codex\nA later human-authored line."), self.setup))

    def test_an_empty_marker_never_matches(self):
        self.assertFalse(sweep.agent_footer(
            "A human-authored line.", {"AGENT_FOOTERS": ["", "  "]}))

    def test_no_footers_configured_matches_nothing(self):
        self.assertFalse(sweep.agent_footer("Generated by Codex", {}))

    def test_anyone_but_USER_always_answers(self):
        self.assertTrue(sweep.answered(
            self.comment(None, user="toumix-agents"), self.setup))

    def test_a_body_USER_wrote_with_no_footer_is_unanswered(self):
        self.assertFalse(sweep.answered(
            self.comment("what did Evening do?"), self.setup))


class Stale(unittest.TestCase):
    """A note carries the date it was read, so staleness is arithmetic rather
    than discipline — the drift no amount of "remember to check" ever fixed."""

    def test_a_note_read_after_its_item_moved_is_current(self):
        self.assertEqual(sweep.stale({489: "2026-09-01"},
                                     {489: "2026-08-30T12:00:00Z"}), [])

    def test_same_day_is_current_whatever_the_hour(self):
        self.assertEqual(sweep.stale({489: "2026-09-01"},
                                     {489: "2026-09-01T23:59:59Z"}), [])

    def test_an_item_that_moved_a_day_later_is_stale(self):
        self.assertEqual(sweep.stale({489: "2026-08-31"},
                                     {489: "2026-09-01T00:00:01Z"}), [489])

    def test_a_note_with_no_readable_date_cannot_say_when_it_was_true(self):
        self.assertEqual(sweep.stale({489: None},
                                     {489: "2026-09-01T00:00:00Z"}), [489])

    def test_a_note_whose_item_is_not_open_is_not_stale_but_orphan(self):
        self.assertEqual(sweep.stale({676: "2020-01-01"}, {}), [])


class ReadDate(unittest.TestCase):
    """The `read <date>` field of a `WORK/` note, which is the whole of the
    staleness arithmetic: a date the parser cannot see is a note reported as
    stale every sweep until a turn hand-edits a date that was already right."""

    def test_the_field_as_the_template_writes_it(self):
        self.assertEqual(
            sweep.read_date("- **state** ready · read 2026-09-18"),
            "2026-09-18")

    def test_a_wrapped_state_line_still_carries_it(self):
        """What a 100-column fill does to `WORK/TEMPLATE.md`'s state line,
        which is long enough to wrap."""
        self.assertEqual(sweep.read_date(
            "- **state** ready · `blocked` · 96/23 across 7 files · read\n"
            "  2026-09-24"), "2026-09-24")

    def test_two_spaces_are_still_one_field(self):
        self.assertEqual(sweep.read_date("read  2026-09-18"), "2026-09-18")

    def test_an_emphasised_date_is_a_date(self):
        """`WORK/discopy/659.md` on 2026-09-25: the freshest note in the
        directory, bolded to stand out, reported as never read."""
        self.assertEqual(sweep.read_date("· read **2026-09-25 00:3xZ**"),
                         "2026-09-25")

    def test_a_time_after_the_date_is_ignored(self):
        self.assertEqual(sweep.read_date("read 2026-09-25 03:5xZ"),
                         "2026-09-25")

    def test_prose_between_the_field_and_the_date_is_not_the_field(self):
        """The field is `read <date>`; a note is free to write prose elsewhere
        on the line, and an undated note is the honest reading of one."""
        self.assertIsNone(sweep.read_date("re-read live 2026-09-18"))

    def test_a_date_nobody_read_is_not_a_read_date(self):
        self.assertIsNone(sweep.read_date(
            "- **2026-09-19 🌙 Evening** re-merged `main`"))

    def test_a_note_with_no_date_at_all_carries_none(self):
        self.assertIsNone(sweep.read_date("# discopy#489\n\n- **state** ready"))

    def test_the_first_field_wins_over_a_later_one(self):
        """The state line is at the top of the note and the log below it, so
        the newest reading is the one the note opens with."""
        self.assertEqual(sweep.read_date(
            "- **state** read 2026-09-25\n- **2026-09-01** read 2026-09-01"),
            "2026-09-25")


class Staleness(unittest.TestCase):
    """The two findings `stale` returns as one list, told apart: no date wants
    a date written, an old date wants the head re-read."""

    def test_an_old_date_says_the_item_moved(self):
        self.assertEqual(sweep.staleness(489, "2026-08-31"),
                         "was read 2026-08-31 and 489 moved since, so it may"
                         " be stale")

    def test_no_date_says_so_rather_than_printing_None(self):
        self.assertEqual(sweep.staleness(489, None),
                         "carries no read date, so nothing says when it was"
                         " true — write one")
        self.assertNotIn("None", sweep.staleness(489, None))


class BaseSha(unittest.TestCase):
    """The `base <sha>` field of a `WORK/` note: the tip its checks ran
    against, so a reader of the note can do the arithmetic `arrears` does live.
    Carrying none is silent, which is why the parser must not guess."""

    def test_the_field_as_the_template_writes_it(self):
        self.assertEqual(sweep.base_sha(
            "- **state** ready · 0 behind `main` · base 4d96025 ·"
            " read 2026-09-27"), "4d96025")

    def test_a_sha_in_backticks_and_emphasis_is_the_field(self):
        self.assertEqual(sweep.base_sha("· base **`4d96025`** ·"), "4d96025")

    def test_a_full_sha_is_the_field(self):
        self.assertEqual(
            sweep.base_sha("base 4d96025149cda6b222006a27a81d25ca4beb9474"),
            "4d96025149cda6b222006a27a81d25ca4beb9474")

    def test_a_ref_between_the_field_and_its_sha_is_not_the_field(self):
        """`base `main`@`4d96025`` puts prose between the two, so it carries no
        sha the sweep can see: the ref is named elsewhere on the line."""
        self.assertIsNone(sweep.base_sha("· base `main`@`4d96025` ·"))

    def test_a_branch_name_is_not_a_sha(self):
        self.assertIsNone(sweep.base_sha("- **state** 0 behind base `main`"))

    def test_prose_about_a_base_carries_no_sha(self):
        self.assertIsNone(sweep.base_sha(
            "- **2026-09-19 🌙 Evening** its base moved three commits"))

    def test_a_note_predating_the_field_carries_none(self):
        self.assertIsNone(sweep.base_sha(
            "- **state** ready · `blocked` · read 2026-09-18"))


class Unmerged(unittest.TestCase):
    """Sign-off condition 2, which nothing checked before desire#32: *CI green
    on the real jobs, with the target branch merged in.* Arrears against a
    head's own base is the head's failure, a note recording another base is the
    note's, and the two want different work."""

    def test_a_head_level_with_its_own_base_holds(self):
        self.assertIsNone(sweep.unmerged(0, "4d96025aa", None))

    def test_one_commit_of_arrears_is_a_merge_nobody_will_perform(self):
        """discopy#660 on 2026-09-19: three behind `split/2`, green since
        09-12, called ready by three notes and two boards."""
        self.assertEqual(
            sweep.unmerged(3, "bb99e4e2a4d4", None),
            "is 3 commit(s) behind its own base bb99e4e, so every check on it"
            " ran against a merge nobody will perform — condition 2 is stale,"
            " not green")

    def test_a_current_head_whose_note_records_another_base(self):
        self.assertEqual(
            sweep.unmerged(0, "4d96025149cd", "66d01e3"),
            "is current, and its note still records base 66d01e3 where the"
            " base is now 4d96025 — re-read the note, not the head")

    def test_an_abbreviated_sha_agrees_with_the_tip_it_abbreviates(self):
        self.assertIsNone(sweep.unmerged(0, "4d96025149cda6b2", "4d96025"))

    def test_a_note_with_no_base_field_says_nothing_either_way(self):
        """103 notes predate the field; a finding on each would drown the one
        note that is wrong."""
        self.assertIsNone(sweep.unmerged(0, "4d96025", None))

    def test_arrears_outrank_the_note(self):
        """A head that owes a merge-down owes it whatever its note says, and
        one finding per head is what a turn can act on."""
        self.assertIn("behind its own base",
                      sweep.unmerged(3, "bb99e4e", "66d01e3"))


class Waiting(unittest.TestCase):
    """`AGENTS.md`'s third sign-off condition — every review thread resolved or
    waiting on human feedback — as a function rather than as whichever turn
    happens to open the head and look."""

    def setUp(self):
        self.setup = {
            "USER": "toumix",
            "AGENT_FOOTERS": ["claude.ai/code", "Generated by Codex"],
        }
        self.comments = {}

    def said(self, number, user, body, at="2026-09-01T00:00:00Z"):
        self.comments[number] = {
            "id": number, "user": {"login": user}, "body": body,
            "created_at": at, "html_url": f"https://example/c/{number}"}
        return number

    def thread(self, *ids, resolved=False, path="discopy/matrix.py"):
        return {"resolved": resolved, "path": path, "comment_ids": list(ids)}

    def paths(self, *threads):
        return [thread["path"] for thread, _ in
                sweep.waiting(list(threads), self.comments, self.setup)]

    def test_a_resolved_thread_is_settled_whoever_spoke_last(self):
        bot = self.said(1, "discopy[bot]", "drop the backticks")
        self.assertEqual(self.paths(self.thread(bot, resolved=True)), [])

    def test_a_bot_with_the_last_word_waits_on_us(self):
        """discopy#661 carried eleven of these, none younger than a fortnight,
        while three notes and four boards called the head ready."""
        bot = self.said(1, "discopy[bot]", "drop the backticks")
        self.assertEqual(self.paths(self.thread(bot)), ["discopy/matrix.py"])

    def test_our_own_reply_leaves_the_thread_waiting_on_a_human(self):
        bot = self.said(1, "discopy[bot]", "drop the backticks")
        ours = self.said(2, "toumix", "Done.\n\n_Generated by [Claude Code]"
                         "(https://claude.ai/code)_", at="2026-09-02T00:00:00Z")
        self.assertEqual(self.paths(self.thread(bot, ours)), [])

    def test_USER_with_the_last_word_is_left_to_asking(self):
        """`asking` already reports it and a 👀 quiets it; saying it here would
        report the same thread twice and un-quiet the ones already in hand."""
        ours = self.said(1, "toumix", "Fixed.\n\n_Generated by [Claude Code]"
                         "(https://claude.ai/code)_")
        user = self.said(2, "toumix", "i think this is the wrong fix",
                         at="2026-09-02T00:00:00Z")
        self.assertEqual(self.paths(self.thread(ours, user)), [])

    def test_another_human_with_the_last_word_waits_on_us(self):
        them = self.said(1, "toumix-agents", "this breaks rotation")
        self.assertEqual(self.paths(self.thread(them)), ["discopy/matrix.py"])

    def test_the_last_word_is_the_newest_not_the_listed_last(self):
        bot = self.said(2, "discopy[bot]", "drop the backticks",
                        at="2026-09-03T00:00:00Z")
        ours = self.said(1, "toumix", "Done.\n\n_Generated by [Claude Code]"
                         "(https://claude.ai/code)_", at="2026-09-02T00:00:00Z")
        self.assertEqual(self.paths(self.thread(ours, bot)),
                         ["discopy/matrix.py"])

    def test_an_unreadable_thread_is_reported_not_assumed_settled(self):
        """Treating what we cannot read as resolved is the mistake the whole
        check exists to stop making."""
        thread = self.thread(404)
        self.assertEqual(
            sweep.waiting([thread], self.comments, self.setup), [(thread, None)])


class Cited(unittest.TestCase):
    """Forming a view on one item pulls in what it references: that is how an
    issue earns a note without a human deciding it has."""

    def test_numbers_are_read_out_of_prose(self):
        self.assertEqual(sweep.cited("a/b", ["waits on #625, blocks #443"]),
                         {625, 443})

    def test_every_note_contributes(self):
        self.assertEqual(sweep.cited("a/b", ["#1", "#2 and #1"]), {1, 2})

    def test_a_note_citing_nothing_pulls_in_nothing(self):
        self.assertEqual(sweep.cited("a/b", ["no numbers here"]), set())

    def test_a_citation_naming_another_repo_is_that_repo_s(self):
        """`WORK/discopy/661.md` cites `desire#26`, which said nothing about
        discopy's own #26 — the sweep asked for a note on it every night."""
        self.assertEqual(sweep.cited("discopy/discopy", ["waits on desire#26"]),
                         set())
        self.assertEqual(
            sweep.cited("discopy/discopy",
                        ["[desire#26](https://github.com/o/desire/issues/26)"]),
            set())

    def test_this_repo_named_in_full_or_short_still_counts(self):
        self.assertEqual(sweep.cited("discopy/discopy", ["discopy#661"]), {661})
        self.assertEqual(
            sweep.cited("discopy/discopy", ["discopy/discopy#661"]), {661})

    def test_an_anchor_or_a_url_fragment_is_not_a_citation(self):
        self.assertEqual(sweep.cited("a/b", ["README.md#ready", "p/1#issue-2"]),
                         set())


class Notes(unittest.TestCase):
    """`notes` is the whole rule: one file per open item, deleted when the
    item is not open any more."""

    def test_agreement_is_silent(self):
        self.assertEqual(sweep.notes({489, 443}, {443, 489}), ([], []))

    def test_an_item_with_no_note_is_missing(self):
        self.assertEqual(sweep.notes({489}, {489, 443}), ([443], []))

    def test_a_note_with_no_open_item_is_an_orphan(self):
        self.assertEqual(sweep.notes({489, 676}, {489}), ([], [676]))

    def test_both_at_once_and_sorted(self):
        self.assertEqual(sweep.notes({9, 2}, {3, 1}), ([1, 3], [2, 9]))

    def test_nothing_open_makes_every_note_an_orphan(self):
        self.assertEqual(sweep.notes({1, 2}, set()), ([], [1, 2]))


class MemoryClone(unittest.TestCase):
    """The memory clone is wherever the `config.env` we are configured by
    sits, so there is one answer rather than two that can disagree. A sweep
    against a memory repo carrying no `WORK/` still sweeps and says so, rather
    than reporting every open item as missing its note."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = pathlib.Path(self.directory.name)

    def configured_by(self, path):
        os.environ["AGENTS_CONFIG"] = str(path)
        self.addCleanup(os.environ.pop, "AGENTS_CONFIG", None)

    def test_the_clone_is_the_config_file_s_own_directory(self):
        (self.root / "WORK").mkdir()
        (self.root / "config.env").write_text("MEMORY_REPO=someone/memory\n")
        self.configured_by(self.root / "config.env")
        self.assertEqual(sweep.memory_clone(), self.root)

    def test_a_clone_without_WORK_is_not_one_we_can_check(self):
        (self.root / "config.env").write_text("MEMORY_REPO=someone/memory\n")
        self.configured_by(self.root / "config.env")
        self.assertIsNone(sweep.memory_clone())

    def test_a_config_path_that_does_not_exist_is_none(self):
        self.configured_by(self.root / "nowhere" / "config.env")
        self.assertIsNone(sweep.memory_clone())


class NotedBase(unittest.TestCase):
    """`noted_base` reads the field off the note of one item, and answers
    `None` for every way a note can fail to carry one — no clone, no note, no
    field — because carrying none is silent rather than a finding."""

    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = pathlib.Path(self.directory.name)
        (self.root / "WORK" / "discopy").mkdir(parents=True)
        (self.root / "config.env").write_text("MEMORY_REPO=someone/memory\n")
        os.environ["AGENTS_CONFIG"] = str(self.root / "config.env")
        self.addCleanup(os.environ.pop, "AGENTS_CONFIG", None)

    def note(self, number, text):
        (self.root / "WORK" / "discopy" / f"{number}.md").write_text(text)

    def test_the_field_off_the_note_of_that_item(self):
        self.note(660, "- **state** ready · base bb99e4e · read 2026-09-27")
        self.assertEqual(sweep.noted_base("discopy/discopy", 660), "bb99e4e")

    def test_an_item_with_no_note_carries_no_base(self):
        self.assertIsNone(sweep.noted_base("discopy/discopy", 660))

    def test_a_note_predating_the_field_carries_no_base(self):
        self.note(660, "- **state** ready · `blocked` · read 2026-09-18")
        self.assertIsNone(sweep.noted_base("discopy/discopy", 660))

    def test_the_directory_is_the_repo_name_alone(self):
        """`WORK/<name>/`, not `WORK/<owner>/<name>/`, the same key `uncharted`
        globs — so a note read here is the note reported there."""
        self.note(660, "· base bb99e4e ·")
        self.assertIsNone(sweep.noted_base("rel-int/discopy", 661))
        self.assertEqual(sweep.noted_base("rel-int/discopy", 660), "bb99e4e")


class Config(unittest.TestCase):
    """`config.env` is the one file naming USER, AGENT and the repos, so a
    malformed line raises rather than parsing to a key nobody reads."""

    def parse(self, text):
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        path = pathlib.Path(directory.name) / "config.env"
        path.write_text(text)
        return sweep.config(path)

    def test_values_keep_everything_after_the_first_equals(self):
        self.assertEqual(self.parse("AGENT_EMAIL=a=b@c\n")["AGENT_EMAIL"],
                         "a=b@c")

    def test_work_repos_is_a_list(self):
        self.assertEqual(self.parse("WORK_REPOS=a/b,c/d\n")["WORK_REPOS"],
                         ["a/b", "c/d"])

    def test_footers_are_a_list_and_keep_their_spaces(self):
        self.assertEqual(
            self.parse("AGENT_FOOTERS=claude.ai/code,Generated by Codex\n")
            ["AGENT_FOOTERS"], ["claude.ai/code", "Generated by Codex"])

    def test_an_empty_footer_entry_is_dropped(self):
        self.assertEqual(self.parse("AGENT_FOOTERS=a,, ,b\n")["AGENT_FOOTERS"],
                         ["a", "b"])

    def test_adopted_prs_maps_repo_to_numbers(self):
        self.assertEqual(self.parse("ADOPTED_PRS=a/b:1,2 c/d:3\n")
                         ["ADOPTED_PRS"], {"a/b": [1, 2], "c/d": [3]})

    def test_an_empty_adopted_prs_is_no_repo(self):
        self.assertEqual(self.parse("ADOPTED_PRS=\n")["ADOPTED_PRS"], {})

    def test_comments_and_blank_lines_are_skipped(self):
        """The seed in `template/memory/config.env` ships commented, and the
        file is edited by hand, so a `#` line is not a malformed setting."""
        self.assertEqual(self.parse(
            "# what this file is\n\nUSER=toumix\n  # indented\nAGENT=agents\n"),
            {"USER": "toumix", "AGENT": "agents"})

    def test_a_hash_inside_a_value_is_kept(self):
        self.assertEqual(self.parse("APPROVE_EMOJI=rocket # not a comment\n")
                         ["APPROVE_EMOJI"], "rocket # not a comment")

    def test_a_line_with_no_key_raises(self):
        with self.assertRaises(ValueError):
            self.parse("USER=toumix\nnot a setting\n")


class ReviewComments(unittest.TestCase):
    """Whether an item has review comments is read off the item, not guessed
    from a status code: GitHub numbers issues and pulls in one space, and only
    a pull carries `pull_request`."""

    def setUp(self):
        self.asked = []
        original = sweep.get
        sweep.get = lambda repo, path: self.asked.append(path) or []
        self.addCleanup(setattr, sweep, "get", original)

    def test_an_issue_is_never_asked_about_on_the_pulls_endpoint(self):
        self.assertEqual(sweep.review_comments("a/b", 87, {}), [])
        self.assertEqual(self.asked, [])

    def test_a_pull_request_is(self):
        sweep.review_comments("a/b", 136, {"pull_request": {}})
        self.assertEqual(self.asked, ["pulls/136/comments"])

    def test_a_forbidden_listing_is_raised_not_read_as_an_issue(self):
        """A gateway answers 403 where GitHub answers 404, so a listing
        nobody read must never pass for one with no comments in it."""
        def forbidden(repo, path):
            raise urllib.error.HTTPError(path, 403, "Forbidden", {}, None)
        sweep.get = forbidden
        with self.assertRaises(urllib.error.HTTPError):
            sweep.review_comments("a/b", 136, {"pull_request": {}})


class Memory(unittest.TestCase):
    """One open day PR per day is the invariant. Siblings with distinct titles
    are USER not having merged, no finding; two under one title is a day written
    twice, which is. Whenever any are open the newest by `created_at` is named
    as the branch to stack a new day's PR on, not `main` (desire#144)."""

    def patch(self, pulls):
        original = sweep.get
        sweep.get = lambda repo, path: pulls
        self.addCleanup(setattr, sweep, "get", original)

    def pull(self, title, ref, created_at):
        return {"title": title, "html_url": f"u/{ref}",
                "head": {"ref": ref}, "created_at": created_at}

    def run_memory(self):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            findings = sweep.memory("a/memory")
        return findings, stderr.getvalue()

    def test_siblings_with_distinct_titles_are_no_finding(self):
        self.patch([self.pull("2026-09-07", "b", "2026-09-07T00:00:00Z"),
                    self.pull("2026-09-04", "a", "2026-09-04T00:00:00Z")])
        findings, _ = self.run_memory()
        self.assertEqual(findings, [])

    def test_two_under_one_title_is_a_finding(self):
        self.patch([self.pull("2026-09-07", "b", "2026-09-07T00:00:00Z"),
                    self.pull("2026-09-07", "a", "2026-09-07T01:00:00Z")])
        findings, _ = self.run_memory()
        self.assertEqual(len(findings), 1)
        self.assertIn("2026-09-07", findings[0])

    def test_the_newest_open_branch_is_named_to_stack_on(self):
        self.patch([self.pull("2026-09-04", "older", "2026-09-04T00:00:00Z"),
                    self.pull("2026-09-07", "newest", "2026-09-07T00:00:00Z")])
        _, err = self.run_memory()
        self.assertIn("'newest'", err)
        self.assertNotIn("'older'", err)

    def test_no_open_prs_names_no_branch(self):
        self.patch([])
        findings, err = self.run_memory()
        self.assertEqual(findings, [])
        self.assertNotIn("base a new day's PR", err)


class Everywhere(unittest.TestCase):
    """`AGENTS.md` asks for the sweep over every repo in play, and nothing
    enumerated them: `WORK_REPOS` was parsed and then only ever membership
    tested against the repo the agent had typed (desire#30)."""

    def test_memory_then_desire_then_the_work_repos(self):
        self.assertEqual(sweep.everywhere({
            "MEMORY_REPO": "u/memory", "DESIRE_REPO": "u/desire",
            "WORK_REPOS": ["u/desire", "o/work", "o/other"]}),
            ["u/memory", "u/desire", "o/work", "o/other"])

    def test_desire_being_a_work_repo_names_it_once(self):
        """Which it is in the live config, so the list would otherwise sweep it
        twice and take minutes doing it."""
        self.assertEqual(sweep.everywhere({
            "MEMORY_REPO": "u/memory", "DESIRE_REPO": "u/desire",
            "WORK_REPOS": ["u/desire"]}), ["u/memory", "u/desire"])

    def test_a_key_the_config_does_not_set_drops_out(self):
        self.assertEqual(sweep.everywhere({"WORK_REPOS": ["o/work"]}),
                         ["o/work"])

    def test_the_configured_file_names_every_repo_in_play(self):
        """Whatever `config.env` holds, here or in the seed: the list is what
        the file says, and this script hard-codes no repo."""
        setup = sweep.config(sweep.find_config())
        in_play = sweep.everywhere(setup)
        self.assertEqual(in_play[:2],
                         [setup["MEMORY_REPO"], setup["DESIRE_REPO"]])
        self.assertEqual(set(in_play), {setup["MEMORY_REPO"],
                                        setup["DESIRE_REPO"],
                                        *setup["WORK_REPOS"]})


class Coverage(unittest.TestCase):
    """`clean` is a claim about the configuration, not about whatever the agent
    typed: twenty-two turns swept three of four WORK_REPOS and read the word
    clean, and the two repos nobody could read were invisible in the output
    (desire#30)."""

    def setUp(self):
        self.setup = {"MEMORY_REPO": "u/memory", "DESIRE_REPO": "u/desire",
                      "WORK_REPOS": ["u/desire", "o/work"]}
        self.all = ["u/memory", "u/desire", "o/work"]

    def verdict(self, asked, numbers=(), unreadable=(), findings=()):
        return sweep.coverage(list(asked), list(numbers), list(unreadable),
                              list(findings), self.setup)

    def test_everything_read_and_nothing_found_is_clean(self):
        self.assertEqual(self.verdict(self.all), "clean")

    def test_one_repo_of_three_never_says_clean(self):
        verdict = self.verdict(["o/work"])
        self.assertNotIn("clean", verdict)
        self.assertIn("no finding in o/work", verdict)
        self.assertIn("not asked about: u/memory, u/desire", verdict)

    def test_a_repo_nobody_could_read_never_says_clean(self):
        verdict = self.verdict(self.all, unreadable=["o/work"])
        self.assertNotIn("clean", verdict)
        self.assertIn("unreadable: o/work", verdict)
        self.assertIn("in u/memory, u/desire", verdict)

    def test_naming_items_is_not_sweeping_the_repo(self):
        self.assertIn("in o/work #12 #13",
                      self.verdict(["o/work"], numbers=[12, 13]))

    def test_findings_are_counted_and_the_scope_still_said(self):
        self.assertEqual(self.verdict(self.all, findings=["a", "b"]),
                         "2 finding(s) in u/memory, u/desire, o/work")

    def test_nothing_read_at_all_says_so(self):
        self.assertIn("anywhere: nothing was read",
                      self.verdict(["o/work"], unreadable=["o/work"]))


class Everything(unittest.TestCase):
    """`sweep.py` with no repo argument sweeps every repo in play, and one
    denied repo is a line of its own rather than the whole run's verdict: the
    old `main` returned 2 on the first failure and printed none of what the
    readable repos had found."""

    def setUp(self):
        self.swept = []
        original = sweep.sweep
        sweep.sweep = self.fake
        self.addCleanup(setattr, sweep, "sweep", original)
        self.config = pathlib.Path(tempfile.mkdtemp()) / "config.env"
        self.config.write_text("MEMORY_REPO=u/memory\nDESIRE_REPO=u/desire\n"
                               "WORK_REPOS=u/desire,o/work,o/denied\n")
        os.environ["AGENTS_CONFIG"] = str(self.config)
        self.addCleanup(os.environ.pop, "AGENTS_CONFIG", None)

    def fake(self, repo, numbers, since, setup):
        self.swept.append(repo)
        if repo == "o/denied":
            raise urllib.error.HTTPError(repo, 403, "Forbidden", {}, None)
        return [f"{repo}#1 something"] if repo == "o/work" else []

    def run_main(self, arguments):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            code = sweep.main(arguments)
        return code, stderr.getvalue()

    def test_no_argument_sweeps_every_repo_in_play(self):
        code, err = self.run_main([])
        self.assertEqual(self.swept, ["u/memory", "u/desire", "o/work",
                                      "o/denied"])
        self.assertEqual(code, 2)
        self.assertIn("o/work#1 something", err)
        self.assertIn("unreadable: o/denied", err)

    def test_the_denial_does_not_hide_the_other_repos_findings(self):
        _, err = self.run_main([])
        self.assertLess(err.index("o/work#1 something"),
                        err.rindex("o/denied"))

    def test_one_repo_still_sweeps_only_that_one_and_exits_zero(self):
        """Sweeping the slow repo alone is how a turn is meant to work, so it
        stays exit 0 — the verdict line is what says it covered one of four."""
        code, err = self.run_main(["u/desire"])
        self.assertEqual((self.swept, code), (["u/desire"], 0))
        self.assertIn("not asked about: u/memory, o/work, o/denied", err)

    def test_since_is_still_read_off_the_front(self):
        code, _ = self.run_main(
            ["--since", "2026-09-27T00:00:00Z", "u/desire"])
        self.assertEqual((self.swept, code), (["u/desire"], 0))

    def test_since_alone_sweeps_everything(self):
        self.run_main(["--since", "2026-09-27T00:00:00Z"])
        self.assertEqual(len(self.swept), 4)


class Transport(unittest.TestCase):
    """A read nobody answered is done again; a read GitHub answered is not.
    The two used to be one case and neither was handled: a
    `RemoteDisconnected` is a `ConnectionResetError` and an `HTTPException`
    and is no kind of `URLError`, so it walked through the guard in `main`
    written for exactly it, and ended a sweep of five repos with a traceback
    on the one hundred and eighty-third read."""

    def setUp(self):
        self.attempts = []
        original = urllib.request.urlopen
        urllib.request.urlopen = self.urlopen
        self.addCleanup(setattr, urllib.request, "urlopen", original)
        self.addCleanup(setattr, sweep, "BACKOFF", sweep.BACKOFF)
        sweep.BACKOFF = 0  # the waiting is not what these tests are about

    def urlopen(self, request):
        self.attempts.append(request.full_url)
        failure = self.failures.pop(0) if self.failures else None
        if failure is not None:
            raise failure
        return io.StringIO(json.dumps(self.answer))

    def read(self, failures, answer=None):
        self.failures, self.answer = list(failures), answer
        return sweep.read(urllib.request.Request("https://api.github.com/x"))

    def test_a_dropped_connection_is_read_again(self):
        dropped = http.client.RemoteDisconnected("closed without response")
        self.assertEqual(self.read([dropped], answer=[{"number": 7}]),
                         [{"number": 7}])
        self.assertEqual(len(self.attempts), 2)

    def test_a_reset_and_a_timeout_are_the_same_case(self):
        self.assertEqual(
            self.read([ConnectionResetError(), TimeoutError(),
                       urllib.error.URLError("unreachable")], answer=[]),
            [])
        self.assertEqual(len(self.attempts), sweep.ATTEMPTS)

    def test_a_forbidden_read_is_raised_on_the_first_attempt(self):
        """GitHub answering no is an answer, and the rest of this file reads
        the status code off it: retrying one would turn a 403 into four and
        tell the caller nothing it did not already know."""
        self.failures = [urllib.error.HTTPError("u", 403, "Forbidden", {},
                                                None)]
        self.answer = []
        with self.assertRaises(urllib.error.HTTPError):
            sweep.read(urllib.request.Request("https://api.github.com/x"))
        self.assertEqual(len(self.attempts), 1)

    def test_a_read_nobody_ever_answers_is_raised_not_swallowed(self):
        with self.assertRaises(http.client.RemoteDisconnected):
            self.read([http.client.RemoteDisconnected()] * sweep.ATTEMPTS)
        self.assertEqual(len(self.attempts), sweep.ATTEMPTS)


class Dropped(unittest.TestCase):
    """What a drop that outlives its retries costs: the repo is unreadable and
    the sweep exits 2. Exit 1 would be the lie — it is the code for findings,
    and a traceback used to land on it."""

    def setUp(self):
        original = sweep.sweep
        sweep.sweep = self.fake
        self.addCleanup(setattr, sweep, "sweep", original)
        self.config = pathlib.Path(tempfile.mkdtemp()) / "config.env"
        self.config.write_text("MEMORY_REPO=u/memory\nDESIRE_REPO=u/desire\n"
                               "WORK_REPOS=u/desire,o/work\n")
        os.environ["AGENTS_CONFIG"] = str(self.config)
        self.addCleanup(os.environ.pop, "AGENTS_CONFIG", None)

    def fake(self, repo, numbers, since, setup):
        if repo == "o/work":
            raise http.client.RemoteDisconnected("closed without response")
        return []

    def run_main(self):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            code = sweep.main([])
        return code, stderr.getvalue()

    def test_the_drop_is_a_line_and_the_verdict_is_two(self):
        code, err = self.run_main()
        self.assertEqual(code, 2)
        self.assertIn("o/work: GitHub unreadable", err)
        self.assertIn("unreadable: o/work", err)

    def test_the_other_repos_are_still_swept(self):
        _, err = self.run_main()
        self.assertNotIn("clean", err)


if __name__ == "__main__":
    unittest.main()
