import unittest

from sweep import CONFIG, agent_footer, answered, config


class FooterTest(unittest.TestCase):
    def setUp(self):
        self.setup = {
            "USER": "toumix",
            "AGENT_FOOTER": "Generated by Codex",
            "AGENT_FOOTER_ALIASES": ["claude.ai/code"],
        }

    def comment(self, body, user="toumix"):
        return {"body": body, "user": {"login": user}}

    def test_config_has_current_and_historical_footers(self):
        setup = config(CONFIG)
        self.assertEqual(setup["AGENT_FOOTER"], "Generated by Codex")
        self.assertEqual(setup["AGENT_FOOTER_ALIASES"], ["claude.ai/code"])

    def test_plain_current_footer_answers(self):
        self.assertTrue(answered(
            self.comment("Done.\n\nGenerated by Codex"), self.setup))

    def test_linked_current_footer_answers(self):
        self.assertTrue(answered(self.comment(
            "Done.\n\n[Generated by Codex](https://chatgpt.com/share/example)"),
            self.setup))

    def test_historical_footer_still_answers(self):
        self.assertTrue(answered(self.comment(
            "Done.\n\n_Generated by [Claude Code](https://claude.ai/code)_"),
            self.setup))

    def test_current_marker_in_prose_does_not_answer(self):
        self.assertFalse(answered(self.comment(
            "This line mentions Generated by Codex in prose."), self.setup))

    def test_current_marker_must_be_on_final_line(self):
        self.assertFalse(answered(self.comment(
            "Generated by Codex\nA later human-authored line."), self.setup))

    def test_empty_current_marker_does_not_match(self):
        setup = {**self.setup, "AGENT_FOOTER": "",
                 "AGENT_FOOTER_ALIASES": []}
        self.assertFalse(agent_footer("A human-authored line.", setup))

    def test_non_user_always_answers(self):
        self.assertTrue(answered(
            self.comment(None, user="toumix-agents"), self.setup))


if __name__ == "__main__":
    unittest.main()
